sudo: false

language: python

addons:

matrix:
  include:
    - python: "2.7"

install:
  - pip install coveralls
  - make develop

before_script:

script:
  - make lint
  - make coverage

after_success:
  - coveralls

notifications:
  email:
    russelll@netflix.com
