sudo: false

language: python

addons:

matrix:
  include:
    - python: "3.6"

install:
  - pip install pipenv
  - make develop

before_script:

script:
  - make lint
  - make coverage

after_success:
  - pipenv run coveralls
  - pipenv run coverage report

notifications:
  email:
    russelll@netflix.com
